version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: inventory-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: inventory_db
      MYSQL_USER: root
      MYSQL_PASSWORD: Teamopapa$00
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

volumes:
  mysql_data:
    name: inventory_mysql_data