apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: docker.io/library/inventory-backend-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/inventory_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: root-password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: create-drop
            - name: JWT_SECRET
              value: InventarioSecretKey2024XyZ987654321Ab
            - name: JWT_EXPIRATION
              value: "86400000"