apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: inventory-backend-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/inventory_db
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: create-drop
            - name: JWT_SECRET
              value: InventarioSecretKey2024XyZ987654321Ab
            - name: JWT_EXPIRATION
              value: "86400000"